services:
  db:
    container_name: db
    image: mariadb:10.6.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./_volumes/db/data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD:-rootpassword}"
      MYSQL_DATABASE: "${DB_MYSQL_DATABASE:-wordpress}"
      MYSQL_USER: "${DB_MYSQL_USER:-wordpress}"
      MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD:-wordpress}"
    networks:
      - boilerplate

  web:
    container_name: web
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${DOCKER_WORDPRESS_PORT:-80}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:${DOCKER_DB_PORT:-3306}
      WORDPRESS_DB_USER: "${DB_MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_MYSQL_DATABASE}"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/var/www/html/wp-content/themes/${THEME_NAME}:delegated  # Tema montato localmente
      - ./_volumes/core:/var/www/html                              # Volume nominato per il core di WordPress
      - ./_volumes/plugins:/var/www/html/wp-content/plugins        # Plugin montati localmente
      - ./_volumes/uploads:/var/www/html/wp-content/uploads        # Upload montati localmente
    networks:
      - boilerplate

  cli:
    container_name: cli
    image: wordpress:cli
    depends_on:
      - web
    volumes:
      - ./_volumes/core:/var/www/html                              # Volume nominato per il core di WordPress
      - ./_volumes/plugins:/var/www/html/wp-content/plugins        # Plugin montati localmente
    working_dir: /var/www/html
    entrypoint: ["wp"]
    networks:
      - boilerplate

  mailpit:
    container_name: mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${DOCKER_MAILPIT_PORT:-1025}:1025'
      - '${DOCKER_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    restart: unless-stopped
    networks:
      - boilerplate

networks:
  boilerplate:
    driver: bridge
